# Generated by Django 3.2.8 on 2021-10-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBATransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_column='date/time')),
                ('order_type', models.CharField(blank=True, choices=[('Adjustment', 'Adjustment'), ('FBA Customer Return Fee', 'FBA Customer Return Fee'), ('FBA Inventory Fee', 'FBA Inventory Fee'), ('Order', 'Order'), ('Order_Retrocharge', 'Order_Retrocharge'), ('Refund', 'Refund'), ('Transfer', 'Transfer')], db_column='type', max_length=32, null=True)),
                ('order_id', models.CharField(blank=True, max_length=32, null=True)),
                ('sku', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('order_city', models.CharField(blank=True, max_length=64, null=True)),
                ('order_state', models.CharField(blank=True, max_length=32, null=True)),
                ('order_postal', models.CharField(blank=True, max_length=16, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'db_table': 'fba_transactions',
            },
        ),
    ]
