# Generated by Django 3.2.8 on 2021-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbatransaction',
            name='date_time',
            field=models.DateTimeField(db_column='date_time'),
        ),
    ]
